<a href="https://colab.research.google.com/github/gsalazr/Linear-Algebra-58013/blob/main/LAB_4_SALAZAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

array = np.array([[4,7,8],[-9,0,0],[2,3,4]])
print(array)
int(np.linalg.det(array))

[[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]


36

In [9]:
import numpy as np

A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A, "\n")
int(np.linalg.det(A))
#print(np.linalg.eig)

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]] 



-13

In [10]:
import numpy
A = numpy.array([[2,3,-5],
                  [7,1,-2],
                  [-3,4,1]])
print(A)
print(int(numpy.linalg.det(A)))


[[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]
-140


In [11]:
import numpy
A = numpy.array([[1,2,-1],
                  [4,6,-2],
                  [-1,3,3]])
print(A)
print(int(numpy.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13
