<a href="https://colab.research.google.com/github/gsalazr/Linear-Algebra-58013/blob/main/LAB_9_SALAZAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
print(int(np.linalg.det(A)))

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
print(int(np.linalg.det(B)))


3
-235


In [13]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,3],[4,4,7],[1,1,1]])
z = np.array([[2,4,6],[2,5,7],[1,2,2]])
print(x, "\n")
print(y, "\n")
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3 3]
 [4 4 7]
 [1 1 1]] 

[[2 4 6]
 [2 5 7]
 [1 2 2]]


In [14]:
a = (x.dot(y)).dot(z)
b = x.dot(y.dot(z))

print("(xy)z =", "\n", a)
print("x(yz) =", "\n",b)
print(np.array_equal(a,b))

(xy)z = 
 [[ 74 162 216]
 [197 432 576]
 [320 702 936]]
x(yz) = 
 [[ 74 162 216]
 [197 432 576]
 [320 702 936]]
True


In [15]:
Scale = 2

a = Scale*(z.dot(y))
b = (Scale*z).dot(y)

print("Scale(xy) =", "\n",a)
print("(Scale*x)y =", "\n",b)
print(np.array_equal(a,b))

Scale(xy) = 
 [[52 56 80]
 [62 66 96]
 [24 26 38]]
(Scale*x)y = 
 [[52 56 80]
 [62 66 96]
 [24 26 38]]
True
